name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - .markdownlint-cli2.yaml
      - .lycheeignore
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - "**/*.md"
      - .markdownlint-cli2.yaml
      - .lycheeignore
      - .github/workflows/docs.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --cache --max-retries 3 --exclude-mail './**/*.md'
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
